### ISSUE TITLE
Dynamic values

### ISSUE THREAD

**Issue by Allkorolev** [Dilbert66/esphome-components#14]
Good afternoon, tell me, is the functionality of dynamic values ​​implemented? 

Let me give you an example: there is a number component:

```
number:
  - platform: template
    name: ${upper_devicename} target  temperature
    optimistic: true
    id: target_temp
    min_value: 0
    max_value: 30
    initial_value: 0
    step: 0.1
    restore_value: true
```

This code is setting the target temperature using a slider, tell me if it is possible to set the temperature using a command, for example 

/set_temp 22 or /set_temp 25

22 or 25 is just a dynamic value
