### ISSUE TITLE
Telegram bot missing messages in RX

### ISSUE THREAD

**Issue by fra87** [Dilbert66/esphome-components#2]
Hello

I tried with a basic configuration, mostly taken from the example, just to test the TX and RX.

Transmission of messages works flawlessly.

Reception has some issues, especially when booting after a flashing. I used the "echo" example:

```yaml
        - text: "*" #accept all text messages
          then:
            - logger.log: "MyTest2"
            - telegram.publish:
                message: !lambda |-
                  return "You sent text: " + x.text;
                to: !lambda |-
                  return x.chat_id;
```

But this works only a couple of minutes after flashing, while all the rest (including telegram bot sending) works. If I send a message to the bot 30 seconds after boot the message gets lost; if I send a message to the bot roughly 2 minutes after I get the echo. If I reboot the ESP it works straight ahead, and I haven't tested a power off/on cycle.

It's a bit strange, but do you also get the same behavior?

**Comment by Dilbert66** [comment]
I should put that in the documenation.  The first message after a reboot is ignored on purpose.  Every following one is then accepted.  The reason for this, is that normally on reboot the firmware has no idea what was the last message received ( I will look into storing this value in non-volatile storage at some point), so it retrieves the last message sent and processes that to get the current message number.  The problem with this is that depending on the command sent, will re-execute the last cmd and this is a huge issue if the last cmd was a "reboot" cmd, so the esp will go into a boot loop.  The quick fix I use for now is to ignore the last message/cmd sent in case it's a reboot.  

Now that I think about it I can add logic to determine it's a first boot and ignore reboot cmds and process everything else.  I will look into that and post an update.

**Comment by Dilbert66** [comment]
Ok, i've modified the logic to accept and process the first cmd after logic, but this necessitates a logic change in the yaml section that handles the reboot cmd to check the is_first_cmd flag to ensure that it will only run if this is not the first cmd after a  reboot to prevent a boot loop. Example:
```
    - command: "/reboot,/r"
      then: 
       if:
        condition:
            lambda: 'return !x.is_first_cmd;' #ensure it's not the first cmd after reboot
        then:
            switch.turn_on:  restart_switch
```
Code has been pushed to dev.
